name: Check GitHub Actions

on: workflow_call

permissions: {}

jobs:
  check-actions:
    timeout-minutes: 30
    name: Check GitHub Actions
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.64.0
      - name: Linting
        run: |
          shellcheck --version
          ghalint run
          actionlint -color
