name: Enable auto merge

on:
  - pull_request

permissions:
  contents: read

jobs:
  enable-auto-merge:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    steps:
      - uses: suzuki-shunsuke/enable-auto-merge-action@40ff92c58f505c181294de9417ffadd822667fa5 # main
        with:
          pr_number: ${{github.event.pull_request.number}}
          merge_method: squash
          github_token: ${{github.token}}
